#local_backend: true # npx decap-server
backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"
media_folder: static/img
public_folder: /img
collections:
  - name: pages
    label: Pages
    files:
      - file: "src/content/pages/faq.md"
        label: "FAQ"
        name: "faq"
        format: frontmatter
        fields:
          - { label: "id", name: "id", widget: "hidden" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/content/pages/mentions-legales.md"
        label: "Mentions légales"
        id: "mentions-legales"
        name: "mentions-legales"
        format: frontmatter
        fields:
          - { label: "id", name: "id", widget: "hidden" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: producteur
    label: Producteur
    folder: "src/content/producteurs"
    create: true
    identifier_field: nom
    extension: yml
    fields:
      - { label: "Nom", name: "nom", widget: "string" }
      - { label: "Localisation", name: "localisation", widget: "string" }
      - {
          label: "Catégorie",
          name: "categories",
          widget: "select",
          options: ["Vin", "Bière", "Jus", "Cidre", "Pétillant", "Soft"],
          multiple: true,
        }
      - {
          label: "Type",
          name: "type",
          widget: "select",
          options: ["Local", "National", "Biocoop"],
        }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          media_library: { config: { max_file_size: 100000 } },
          hint: "Hauteur 192px",
        }
      - { label: "Lien", name: "url", widget: "string" }
      - { label: "Format", name: "format", widget: "string", required: false }
      - { label: "Gamme", name: "gamme", widget: "markdown", required: false }
  - name: equipe
    label: Membre de l'équipe
    folder: "src/content/equipe"
    create: true
    identifier_field: nom
    extension: yml
    fields:
      - { label: "Nom", name: "nom", widget: "string" }
      - { label: "Ordre", name: "ordre", widget: "number" }
      - {
          label: "Fonction",
          name: "fonction",
          widget: "string",
          required: false,
        }
      - { label: "Email", name: "email", widget: "string", required: false }
      - {
          label: "Photo",
          name: "photo",
          widget: "image",
          required: false,
          media_library: { config: { max_file_size: 300000 } },
        }
      - {
          label: "Contrat",
          name: "type",
          widget: "select",
          options: ["CDI", "Alternant", "Benevole"],
        }
      - {
          label: "Date entrée",
          name: "date_entree",
          widget: "datetime",
          date_format: "YYYY",
          default: "",
        }
      - {
          label: "Date sortie",
          name: "date_sortie",
          widget: "datetime",
          date_format: "YYYY",
          default: "",
          required: false,
        }
  - name: actu
    label: Actualité
    folder: "src/content/actus"
    create: true
    extension: md
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date de publication", name: "date", widget: "datetime" }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          media_library: { config: { max_file_size: 500000 } },
        }
      - {
          label: "Miniature",
          name: "miniature",
          widget: "image",
          media_library: { config: { max_file_size: 100000 } },
        }
      - { label: "Corps du texte", name: "body", widget: "markdown" }
      - {
          label: "Catégories",
          hint: "Liste de catégories séparées par des virgules",
          name: "categories",
          widget: "list",
        }
  - name: timeline
    label: Contenu de la frise chronologique
    folder: "src/content/timeline"
    create: true
    identifier_field: event
    extension: yml
    fields:
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          date_format: "MMMM YY",
          default: "",
        }
      - { label: "Événement", name: "event", widget: "text" }
  - name: partenaires
    label: Partenaire
    folder: "src/content/partners"
    create: true
    identifier_field: partners
    extension: yml
    fields:
      - { label: "Nom", name: "nom", widget: "string" }
      - { label: "Ordre", name: "ordre", widget: "number" }
      - {
          label: "Logo",
          name: "logo",
          widget: "image",
          media_library: { config: { max_file_size: 300000 } },
        }
      - {
          label: "Logo Noir et Blanc",
          name: "logo_bw",
          widget: "image",
          required: false,
          media_library: { config: { max_file_size: 300000 } },
        }
      - { label: "Lien", name: "lien", widget: "string" }
      - {
          label: "Type",
          name: "type",
          widget: "select",
          options:
            [
              "producteur",
              "distributeur",
              "financier",
              "accompagnement",
              "reseau",
              "logistique",
            ],
        }
  - name: website
    label: Contenu site
    files:
      - file: "src/content/website/home.yml"
        name: "home"
        extension: yml
        label: "Page d'accueil"
        fields:
          - {
              label: Nombre de bouteilles collectées,
              name: "collected_bottles",
              widget: "number",
            }
